export enum CHART_IDS {
  PIE_CHART = "PIE_CHART",
  BAR_CHART = "BAR_CHART",
  MULTI_BAR_CHART = "MULTI_BAR_CHART",
  LINE_CHART = "LINE_CHART",
}

export enum EXTENDED_CHART_TOOLS {
  EXPORT_CSV = "EXPORT_CSV",
  EXPORT_PNG = "EXPORT_PNG",
  EXPORT_SVG = "EXPORT_SVG",
}
