import { ModuleRouteMapping } from "@eGroupAI/typings/apis";
import { RoutesServiceModuleValue } from "interfaces/utils";

const moduleRouteMapping: ModuleRouteMapping<RoutesServiceModuleValue> = {
  COMMON: ["/me"],
  CALENDAR: ["/me/calendar"],
  HRM_MEMBERS: [
    "/me/members/list",
    "/me/members/list/manage",
    "/me/members/list/[memberId]",
    "/me/members/list/[memberId]/events/[eventId]",
  ],
  HRM_ROLES: ["/me/members/roles"],
  ORGANIZATION: ["/me/org-info"],
  ORGANIZATION_GROUP: [
    "/me/org-group",
    "/me/org-group/[groupId]",
    "/me/org-group/tag-groups/[tagGroupId]",
  ],
  CMS_HOMEPAGE: ["/me/cms/home"],
  CMS_ABOUT_US: ["/me/cms/about"],
  CMS_PRODUCT: [
    "/me/cms/products",
    "/me/cms/products/[productId]",
    "/me/cms/products/tag-groups/[tagGroupId]",
  ],
  CMS_SOLUTION: [
    "/me/cms/solutions",
    "/me/cms/solutions/[solutionId]",
    "/me/cms/solutions/tag-groups/[tagGroupId]",
  ],
  CMS_BLOG: [
    "/me/cms/blogs",
    "/me/cms/blogs/[blogId]",
    "/me/cms/blogs/tag-groups/[tagGroupId]",
  ],
  CMS_MENU: [
    "/me/cms/menu",
    "/me/cms/menu/navbar",
    "/me/cms/menu/home",
    "/me/cms/menu/product",
    "/me/cms/menu/blog",
  ],
  TAG: [
    // Old Tag Permissions
    "/me/tag-groups",
    "/me/tag-groups/[tagGroupId]",
    // Temporary Tag Permissions for future approach
    "/me/org-group/tag-groups",
    "/me/org-group/tag-groups/[tagGroupId]",
    "/me/cms/tag-groups",
    "/me/cms/tag-groups/[tagGroupId]",
    "/me/event/events/tag-groups",
    "/me/event/events/tag-groups/[tagGroupId]",
    "/me/crm/users/tag-groups",
    "/me/crm/users/tag-groups/[tagGroupId]",
    "/me/crm/users/finance-tag-management",
    "/me/crm/users/finance-tag-management/[tagGroupId]",
    "/me/crm/partners/tag-groups",
    "/me/crm/partners/tag-groups/[tagGroupId]",
    "/me/bulletins/tag-groups",
    "/me/bulletins/tag-groups/[tagGroupId]",
    "/me/articles/tag-groups",
    "/me/articles/tag-groups/[tagGroupId]",
    "/me/upload-files/tag-groups",
    "/me/upload-files/tag-groups/[tagGroupId]",
    "/me/sms-template/tag-groups",
    "/me/sms-template/tag-groups/[tagGroupId]",
    "/me/ses-template/tag-groups",
    "/me/ses-template/tag-groups/[tagGroupId]",
    "/me/cms/feedbacks/tag-groups",
    "/me/cms/feedbacks/tag-groups/[tagGroupId]",
  ],
  CRM: [],
  CRM_USER: [
    "/me/crm/users",
    "/me/crm/users/[userId]",
    "/me/crm/users/[userId]",
    "/me/crm/users/[userId]/shared/[sharedOrganizationId]",
    "/me/crm/users/tag-groups/[tagGroupId]",
    "/me/crm/users/finance-tag-management/[tagGroupId]",
  ],
  CRM_PARTNER: [
    "/me/crm/partners",
    "/me/crm/partners/[partnerId]",
    "/me/crm/partners/tag-groups/[tagGroupId]",
  ],
  EVENT: [
    "/me/event",
    "/me/event/events",
    "/me/event/events/[eventId]",
    "/me/event/events/tag-groups/[tagGroupId]",
    "/me/event/dashboard",
    "/me/crm/users/[userId]/events/[eventId]",
    "/me/crm/partners/[partnerId]/events/[eventId]",
  ],
  EVENT_REVIEW: [],
  DASHBOARD_CRM: [],
  DASHBOARD_BILLING: [],
  DASHBOARD_FEEDBACK: [],
  DASHBOARD_FILES: [],
  FINANCE_TEMPLATE: ["/me/finance/templates"],
  BILLING: [],
  NOTIFICATION: [],
  PRODUCT: [],
  DYNAMIC_COLUMN: ["/me/dynamic-columns"],
  BULLETIN: [
    "/me/bulletins",
    "/me/bulletins/[bulletinId]",
    "/me/bulletins/[bulletinId]/edit",
    "/me/bulletins/new",
    "/me/bulletins/tag-groups/[tagGroupId]",
  ],
  ARTICLE: [
    "/me/articles",
    "/me/articles/[articleId]",
    "/me/articles/[articleId]/edit",
    "/me/articles/new",
    "/me/articles/tag-groups/[tagGroupId]",
  ],
  FULL_TEXT_SEARCH: ["/me/search"],
  UPLOADFILE: [],
  FILES: [
    "/me/upload-files",
    "/me/upload-files/tag-groups",
    "/me/upload-files/tag-groups/[tagGroupId]",
  ],
  ORDER_MODULE: ["/me/order-module"],
  SMS: ["/me/sms"],
  SES: ["/me/ses"],

  SMS_TEMPLATE: [
    "/me/sms-template",
    "/me/sms-template/[organizationSmsTemplateId]",
    "/me/sms-template/tag-groups/[tagGroupId]",
  ],
  SES_TEMPLATE: [
    "/me/ses-template",
    "/me/ses-template/[organizationSesTemplateId]",
    "/me/ses-template/tag-groups/[tagGroupId]",
  ],

  SETTINGS_PRIVACY: [
    "/me/settings-privacy/setting",
    "/me/settings-privacy/privacy",
    "/me/settings-privacy/activity",
    "/me/settings-privacy/language",
    "/me/settings-privacy",
  ],
  SUPPORT: ["/me/support"],
  FEEDBACK: ["/me/feedback"],
  CMS_FEEDBACK: ["/me/cms/feedbacks", "/me/cms/feedbacks/[feedbackId]"],
  MESSAGES: ["/me/messages"],
};

export default moduleRouteMapping;
